[project]
name = "smol-hack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docling>=2.30.0",
    "litellm>=1.68.0",
    "pytest>=8.3.5",
    "smolagents>=1.14.0",
]
